# Generated by Django 3.2.18 on 2023-04-17 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='candidate_id',
            field=models.CharField(default='_', max_length=10),
        ),
    ]
